AgendaCompromisso/Models/Consultas.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgendaCompromissos.Models {
    public class Consultas {
        [Key]
        public int ConsultaId { get; set; }

        [Required]
        [Column(TypeName = "varchar(250)")]
        public string NomeDoPaciente { get; set; }

        [Required]
        [Column(TypeName = "varchar(10)")]
        public DateTime DataNascimentoPaciente { get; set; } // Data de Nascimento: "dd/mm/aaaa"

        [Required]
        [Column(TypeName = "varchar(16)")]
        public DateTime DataHoraInicial { get; set; } // Data Inicial da Consulta: "dd/mm/aaaa hh:mm"

        [Required]
        [Column(TypeName = "varchar(16)")]
        public DateTime DataHoraFinal { get; set; } // Data Final da Consulta: "dd/mm/aaaa hh:mm"

        [Column(TypeName = "varchar(800)")]
        public string Observacoes { get; set; }

        public Consultas() {
        }

        public Consultas(int id, string paciente, DateTime dataNascimento, DateTime dataHoraInicial, DateTime dataHoraFinal, string obs) {
            ConsultaId = id;
            NomeDoPaciente = paciente;
            DataNascimentoPaciente = dataNascimento;
            DataHoraInicial = dataHoraInicial;
            DataHoraFinal = dataHoraFinal;
            Observacoes = obs;
        }
    }
}

AgendaCompromisso/Models/ErrorViewModel.cs
using System;

namespace AgendaCompromisso.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaCompromisso/Models/ViewModels/ConsultaViewModel.cs
namespace AgendaCompromissos.Models.ViewModels {
    public class ConsultaViewModel {
        public Consultas Consultas { get; set; }
    }
}

AgendaCompromisso/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AgendaCompromissos.Models;
using AgendaCompromissos.Models.ViewModels;
using AgendaCompromissos.Services;
using Microsoft.AspNetCore.Mvc;

namespace AgendaCompromissos.Controllers {
    public class AgendaController : Controller {

        private readonly AgendaService _agendaService;

        public AgendaController(AgendaService agendaService) {
            _agendaService = agendaService;
        }

        public async Task<ActionResult> Index() {
            List<Consultas> lista = await _agendaService.FindAllAsync();
            return View(lista);
        }

        public async Task<ActionResult> Details(int? id) {
            if (id == null) {
                return RedirectToAction(nameof(Error), new { message = "Código da consulta inválido ou nulo." });
            }

            var obj = await _agendaService.FindByIdAsync(id.Value);
            if (obj == null) {
                return RedirectToAction(nameof(Error), new { message = "Código da consulta não localizado." });
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Consultas consulta) {
            if (!ModelState.IsValid) {
                var viewModel = new ConsultaViewModel { Consultas = consulta };
                return View(viewModel);
            }

            //A data final não pode ser menor que a data inicial
            if (consulta.DataHoraFinal <= consulta.DataHoraInicial) {
                return RedirectToAction(nameof(Error), new { message = "Dia e hora final da consulta não permitido" });
            }

            //O sistema não deve permitir o agendamento de duas ou mais consultas no mesmo range de datas
            var obj = await _agendaService.FindByDateAsync(consulta.DataHoraInicial, consulta.DataHoraFinal);

            if (obj == null) {
                await _agendaService.InsertAsync(consulta);
                return RedirectToAction(nameof(Index));
            }
            else {
                return RedirectToAction(nameof(Error), new { message = "Data e hora já agendada para este médico" });
            }
        }

        private object Error() {
            throw new NotImplementedException();
        }

        public ActionResult Create() {
            var viewModel = new ConsultaViewModel() ;

            return View(viewModel);
        }

        public ActionResult Edit(int id) {
            return View();
        }

        public ActionResult Delete(int id) {
            return View();
        }
    }
}

AgendaCompromisso/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AgendaCompromisso.Models;

namespace AgendaCompromisso.Controllers {
    public class HomeController : Controller {
        public IActionResult Index() {
            return View();
        }

        public IActionResult Contact() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgendaCompromisso/Views/Consultas/Create.cshtml
@model AgendaCompromissos.Models.ViewModels.ConsultaViewModel

@{
    ViewData["Title"] = "Cadastro";
}

<h2>Consultas</h2>

<h4>Cadastro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cadastro">
            <div class="form-group">
                <label asp-for="Consultas.NomeDoPaciente" class="control-label"></label>
                <input asp-for="Consultas.NomeDoPaciente" class="form-control" />
                <span asp-validation-for="Consultas.NomeDoPaciente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Consultas.DataNascimentoPaciente" class="control-label"></label>
                <input asp-for="Consultas.DataNascimentoPaciente" class="form-control" />
                <span asp-validation-for="Consultas.DataNascimentoPaciente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Consultas.DataHoraInicial" class="control-label"></label>
                <input asp-for="Consultas.DataHoraInicial" class="form-control" />
                <span asp-validation-for="Consultas.DataHoraInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Consultas.DataHoraFinal" class="control-label"></label>
                <input asp-for="Consultas.DataHoraFinal" class="form-control" />
                <span asp-validation-for="Consultas.DataHoraFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Consultas.Observacoes" class="control-label"></label>
                <input asp-for="Consultas.Observacoes" class="form-control" />
                <span asp-validation-for="Consultas.Observacoes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AgendaCompromisso/Views/Consultas/Index.cshtml
@model IEnumerable<AgendaCompromissos.Models.Consultas>
@{
    ViewData["Title"] = "Consultas";
}
<h2>@ViewData["Title"]</h2>
<p>
    <a asp-action="Create" class="btn btn-default">Nova Consulta</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.NomeDoPaciente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimentoPaciente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataHoraInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataHoraFinal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Observacoes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeDoPaciente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataNascimentoPaciente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataHoraInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataHoraFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Observacoes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ConsultaId">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.ConsultaId">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.ConsultaId">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AgendaCompromisso/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Fale Conosco";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>


<address>
    <strong>Telefone:</strong> (27) 99609-3318<br />
    <strong>E-mail:</strong> <a href="mailto:elyzabeth.alves@gmail.com">elyzabeth.alves@gmail.com</a><br />
</address>

AgendaCompromisso/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Agenda Compromisso";
}

<div>
    <img src="~/images/bg.jpg" class="img-responsive" />
</div>

@*<div class="row">
        <div class="col-md-3">
            <h2>Application uses</h2>
            <ul>
                <li>Sample pages using ASP.NET Core MVC</li>
                <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2>How to</h2>
            <ul>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2>Overview</h2>
            <ul>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2>Run &amp; Deploy</h2>
            <ul>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
            </ul>
        </div>
    </div>*@

AgendaCompromisso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendaCompromisso</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AgendaCompromisso</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Agenda" asp-action="Index">Consultas</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AgendaCompromisso</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>